In [1]:
# what is teh difference between arange and linspace

In [2]:
import numpy as np
a = [2, 5,  7, 9]
print(a)
print(np.array([a]))
# 1. At that point i find out a difference between list and  a numpy array is list print with , between values and np.array with commasa
# 2. in list we can have values of different data types but in np array their show an error so same data type exist

[2, 5, 7, 9]
[[2 5 7 9]]


In [3]:
zeros = np.zeros((3,5))
print(zeros)
# this is use to create a array of zeros 3 is no of rows and 5 is no of columns 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# the answer of my question is understand that in arange difference between values is same but 5 means values from 0 to 10 there the number that print numbers in between array and their difference is last para meterer
step = np.arange(3, 10, 5)
print(step)
# it return a integer value
# in it arange function is used to generate an array and generate points or values two no with same difference.

[3 8]


In [5]:
# in grid linspace function means values of generate krna ha or pir last parameter ka jtna values ko generate krna ha difference unko ka kuck b ho kan hoga vo b same us mn hm mention krtahn ka hmn kitna difference sa valueschahia or is mn hm mention krta hn kahmn kitni valueschahia
grid = np.linspace(0, 10, 5)
print(grid)
# is used to show 5 values from 0 to 1 

[ 0.   2.5  5.   7.5 10. ]


In [6]:
# in list to implement operATION  use loop and append  but in array is int by default

In [7]:
rng = np.random.default_rng(3)
# and every time a new number is generate untill unless a value is pass into rng(?) ? = value thatu wantto enter that every time same random nuber generate ho ya output always same hoo
print(rng.integers(1 , 10))
print(rng.integers(1 , 10))
print(rng.integers(1 , 10))
#  in it rng.integers(1, 10 ) is mn b limit compulsory ha 

8
1
2


In [8]:
arr = np.array([12, 45, 67, 65, 87, 34, 94])
print(arr.size) # to tell the size (no ofvalues) of array
print(arr.ndim) # to tell the dimension as in array is 1D and matrix are multi dimensional
print(arr.shape) # to tell the shape nof of rows and columns in array is 1D so i column and 1 row
print(arr.dtype) # to tell the data type of array and data type of array id also always same means in list different dtypes vary but list single datatype

7
1
(7,)
int32


In [9]:
# Shape, 
a= np.array([[10, 20, 30 ],
            [65, 23, 89]])
print(a.shape)
print(a.ndim) # tell about dimensions of array 
print(a.size) # tell the size of array
print(a.dtype) # tell the data type of the array

(2, 3)
2
6
int32


### Matrices

In [10]:
import numpy as np
m = np.array([[12, 56, 34],
             [23, 15, 00],
             [11, 33, 66]])
print(m[1,1])
# in it first is row index which start from 0 and second is column index which also start from  0

15


In [11]:
print(m[:, :])
# colon is write when all the values of row or column print

[[12 56 34]
 [23 15  0]
 [11 33 66]]


In [12]:
print(m[:, 0])

[12 23 11]


In [13]:
# in simple python time is so much for execution and within seconds by numoy
# by *, +, - or /  two matrix is called broadcasting
matrix = ([[]])

In [14]:
x = np.array([1., 2., 3., 4.])
print(x)
print(x + 10)
print(x ** 2) # ** is power or exponent
print((x - x.mean()) / x.std())  # to find varience

[1. 2. 3. 4.]
[11. 12. 13. 14.]
[ 1.  4.  9. 16.]
[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [15]:
# mask is equivelent to if else condition
np.where 
scores = np.array([45, 68, 72, 91])
new_scores = print(scores[scores >=70]) # by using this syntax mask apply filtering
print(new_scores)
print(np.where(scores >=50, 'pass', 'fail')) # No if else is needed

[72 91]
None
['fail' 'pass' 'pass' 'pass']


In [16]:
## Random simualtion
tosses = rng.choice([0,1], size = 1000)
print('estimated probability of heads:' , tosses.mean())

estimated probability of heads: 0.491


In [17]:
## Random simualtion
tosses = rng.choice([0,1], size = 500)
print('estimated probability of heads:' , tosses.mean())

estimated probability of heads: 0.464


In [18]:
# Numpy Class Activity
# 01 Create a 3 by 4 array containg 1 to 12
a = np.arange(12)
print(a)
b = a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
# Return te second row and last column
c = print(b[ 0:5 ,1:4 ])
# # ar_3 =print(ar_2(1:2, 2:3))
# # print(ar_3)
# # print(m[0:2, 1:3])
# print( b[1,3])
# print(b[ , 1:5])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [21]:
# Numpy Class Activity
# 01 Create a 3 by 4 array containg 1 to 12
a = np.arange(12)
print(a)
b = a.reshape(3, 4)
print(b)
# Return te second row and last column
# ar_3 =print(ar_2(1:2, 2:3))
# print(ar_3)
# print(m[0:2, 1:3])
print( b[1,3])
print(b[0:2 , 1:5])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
[[1 2 3]
 [5 6 7]]


In [22]:
print(b[1: , 0:4])

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
import numpy as np
n = np.arange(16)
print(n)
for i in n:
    if i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(str(i))
    
        


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Fizz
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
Fizz
